#
# Certificates Definition
#  1. For end-point iam.smc.lab.local
#  2. For end-pint portal.smc.lab.local
#

[[tls.certificates]]
   certFile = "/configuration/files/iam.smc.lab.local.cer"
   keyFile = "/configuration/files/iam.smc.lab.local.key"

[[tls.certificates]]
   certFile = "/configuration/files/portal.smc.lab.local.cer"
   keyFile = "/configuration/files/portal.smc.lab.local.key"
